# User Service Configuration
server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1043292028926-i3rd8shi0vtotuafq1hjh57lrm2jg7de.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

# Logging
logging:
  level:
    com.example.user: INFO
    org.springframework.security: DEBUG